package com.xworkz.collections;

import java.util.ArrayList;
import java.util.Collection;

public class ElementsRunner {

	public static void main(String[] args) {
		System.out.println("Festivals");
		System.out.println("-------------------------");

		String festname1 = "diwali";
		String festname2 = "dussehra";
		String festname3 = "holi";
		String festname4 = "pongal";
		String festname5 = "krishna janmashtami";
		String festname6 = "ganesh chathurti";
		String festname7 = "Makar Sankranti";
		String festname8 = "Lohri";
		String festname9 = "Purim";
		String festname10 = "Navroz";
		String festname11 = "Ed milad";
		String festname12 = "bakarid";
		String festname13 = "Ramadan Begins";
		String festname14 = "Ram Navami";
		String festname15 = "Good Friday";
		String festname16 = "Baisakhi";
		String festname17 = "Akshay Tritiya";
		String festname18 = "Buddha Purnima";
		String festname19 = "Raksha Bandhan";
		String festname20 = "Onam";
		String festname21 = "Christmas";
		String festname22 = "Pohela Boishakh";
		String festname23 = "Mahashivratri";
		String festname24 = "Eid-ul-Fitr";
		String festname25 = "Gurpurab";
		String festname26 = "Easter";
		String festname27 = "Hemis";
		String festname28 = "Chhath Puja";
		String festname29 = "Saga Dawa";
		String festname30 = "Dree Festival";
		String festname31 = "Lui-Ngai-Ni";
		String festname32 = "Moatsu Mong";
		String festname33 = "Holika Dahan";
		String festname34 = "Ramanavami";
		String festname35 = "Guru Purnima";
		String festname36 = "Nag Panchami";
		String festname37 = "Varalakshmi Vrat";
		String festname38 = "Navaratri begins";
		String festname39 = "Vishwakarma Puja";
		String festname40 = "Mahalaya Amavasya";
		String festname41 = "Karwa Chauth";
		String festname42 = "Dhan Teras";
		String festname43 = "Bhai Dooj";
		String festname44 = "Dhanu Sankranti";
		String festname45 = "Vaisakhi";
		String festname46 = "Bodhi Day";
		String festname47 = "Nirvana Day";
		String festname48 = "Magha Puja Day";
		String festname49 = "Theravada New Year";
		String festname50 = "Vesak - Buddha Day";
		String festname51 = "Asala - Dharma Day";
		String festname52 = "Obon";
		String festname53 = "Ramadan ";
		String festname54 = "Waqf al Arafa - Hajj";
		String festname55 = "Milad un Nabi";
		String festname56 = "Laylat al Qadr";
		String festname57 = "Muharram";
		String festname58 = "Watch Night";
		String festname59 = "Epiphany";
		String festname60 = "Palm Sunday";

		Collection obj = new ArrayList();
		obj.add(festname1);
		obj.add(festname2);
		obj.add(festname3);
		obj.add(festname4);
		obj.add(festname5);
		obj.add(festname6);
		obj.add(festname7);
		obj.add(festname8);
		obj.add(festname9);
		obj.add(festname10);

		obj.add(festname11);
		obj.add(festname12);
		obj.add(festname13);
		obj.add(festname14);
		obj.add(festname15);
		obj.add(festname16);
		obj.add(festname17);
		obj.add(festname18);
		obj.add(festname19);
		obj.add(festname20);

		obj.add(festname21);
		obj.add(festname22);
		obj.add(festname23);
		obj.add(festname24);
		obj.add(festname25);
		obj.add(festname26);
		obj.add(festname27);
		obj.add(festname28);
		obj.add(festname29);
		obj.add(festname30);

		obj.add(festname31);
		obj.add(festname32);
		obj.add(festname33);
		obj.add(festname34);
		obj.add(festname35);
		obj.add(festname36);
		obj.add(festname37);
		obj.add(festname38);
		obj.add(festname39);
		obj.add(festname40);

		obj.add(festname41);
		obj.add(festname42);
		obj.add(festname43);
		obj.add(festname44);
		obj.add(festname45);
		obj.add(festname46);
		obj.add(festname47);
		obj.add(festname48);
		obj.add(festname49);
		obj.add(festname50);

		obj.add(festname51);
		obj.add(festname52);
		obj.add(festname53);
		obj.add(festname54);
		obj.add(festname55);
		obj.add(festname56);
		obj.add(festname57);
		obj.add(festname58);
		obj.add(festname59);
		obj.add(festname60);

		System.out.println(festname1);
		System.out.println(festname2);
		System.out.println(festname3);
		System.out.println(festname4);
		System.out.println(festname5);
		System.out.println(festname6);
		System.out.println(festname7);
		System.out.println(festname8);
		System.out.println(festname9);
		System.out.println(festname10);
		System.out.println(festname11);
		System.out.println(festname12);
		System.out.println(festname13);
		System.out.println(festname14);
		System.out.println(festname15);
		System.out.println(festname16);
		System.out.println(festname17);
		System.out.println(festname18);
		System.out.println(festname19);
		System.out.println(festname20);
		System.out.println(festname21);
		System.out.println(festname22);
		System.out.println(festname23);
		System.out.println(festname24);
		System.out.println(festname25);
		System.out.println(festname26);
		System.out.println(festname27);
		System.out.println(festname28);
		System.out.println(festname29);
		System.out.println(festname30);
		System.out.println(festname31);
		System.out.println(festname32);
		System.out.println(festname33);
		System.out.println(festname34);

		System.out.println(festname35);
		System.out.println(festname36);
		System.out.println(festname37);
		System.out.println(festname38);
		System.out.println(festname39);
		System.out.println(festname40);
		System.out.println(festname41);
		System.out.println(festname42);
		System.out.println(festname43);
		System.out.println(festname44);
		System.out.println(festname45);
		System.out.println(festname46);
		System.out.println(festname47);
		System.out.println(festname48);
		System.out.println(festname49);
		System.out.println(festname50);
		System.out.println(festname51);
		System.out.println(festname52);
		System.out.println(festname53);
		System.out.println(festname54);
		System.out.println(festname55);
		System.out.println(festname56);
		System.out.println(festname57);
		System.out.println(festname58);
		System.out.println(festname59);
		System.out.println(festname60);
		System.out.println();

		System.out.println("Actors");
		System.out.println("------------------");

		String actor1 = "Amitabh Bachchan";
		String actor2 = "Aamir Khan";
		String actor3 = "Akshay Kumar";
		String actor4 = "Ajay Devgn";
		String actor5 = "Shah Rukh Khan";
		String actor6 = "Irrfan Khan";
		String actor7 = "Hrithik Roshan";
		String actor8 = "Ranbir Kapoor";
		String actor9 = "Shahid Kapoor ";
		String actor10 = "Ranveer Singh ";
		String actor11 = "Sushant Singh Rajput ";
		String actor12 = "Saif Ali Khan ";
		String actor13 = "Abhishek Bachchan";
		String actor14 = "Emraan Hashmi";
		String actor15 = " varun";
		String actor16 = "  Prabhas";
		String actor17 = "N.T. Rama Rao Jr. ";
		String actor18 = " Ram Charan";
		String actor19 = "Mahesh Babu";
		String actor20 = "Pawan Kalyan ";
		String actor21 = " Allu Arjun";
		String actor22 = " Vijay Deverakonda ";
		String actor23 = "Nani ";
		String actor24 = "Naga Chaitanya Akkineni ";
		String actor25 = " Akhil Akkineni";
		String actor26 = "Nagarjuna Akkineni ";
		String actor27 = "Nithiin";
		String actor28 = " Ram Pothineni";
		String actor29 = " Sai Dharam Tej ";
		String actor30 = "Venkatesh Daggubati ";
		String actor31 = " Sudeep";
		String actor32 = "Diganth ";
		String actor33 = " Ajay Rao";
		String actor34 = "Chiranjeevi Sarja ";
		String actor35 = " Vijay Raghavendra";
		String actor36 = "Rakshit Shetty";
		String actor37 = "Puneeth Rajkumar ";
		String actor38 = "Ganesh ";
		String actor39 = " Yash";
		String actor40 = "Aditya ";
		String actor41 = " Prajwal Devaraj";
		String actor42 = " Srinagar Kitty";
		String actor43 = " Prem ";
		String actor44 = "Ramesh Aravind ";
		String actor45 = " Vijay";
		String actor46 = "Brad Pitt ";
		String actor47 = " Tom Cruise";
		String actor48 = "Christian Bale";
		String actor49 = " abrar khazi";
		String actor50 = " zain imam";
		String actor51 = "Edward Norton ";
		String actor52 = "Dhanush";
		String actor53 = "Vijay Sethupathi";
		String actor54 = "Suriya ";
		String actor55 = "Madhavan";
		String actor56 = "Karthi ";
		String actor57 = "Joseph Vijay";
		String actor58 = "Jayam Ravi ";
		String actor59 = "nithin ";
		String actor60 = "siddharth";

		Collection obj1 = new ArrayList();
		obj1.add(actor1);
		obj1.add(actor2);
		obj1.add(actor3);
		obj1.add(actor4);
		obj1.add(actor5);
		obj1.add(actor6);
		obj1.add(actor7);
		obj1.add(actor8);
		obj1.add(actor9);
		obj1.add(actor10);

		obj1.add(actor11);
		obj1.add(actor12);
		obj1.add(actor13);
		obj1.add(actor14);
		obj1.add(actor15);
		obj1.add(actor16);
		obj1.add(actor17);
		obj1.add(actor18);
		obj1.add(actor19);
		obj1.add(actor20);

		obj1.add(actor21);
		obj1.add(actor22);
		obj1.add(actor23);
		obj1.add(actor24);
		obj1.add(actor25);
		obj1.add(actor26);
		obj1.add(actor27);
		obj1.add(actor28);
		obj1.add(actor29);
		obj1.add(actor30);

		obj1.add(actor31);
		obj1.add(actor32);
		obj1.add(actor33);
		obj1.add(actor34);
		obj1.add(actor35);
		obj1.add(actor36);
		obj1.add(actor37);
		obj1.add(actor38);
		obj1.add(actor39);
		obj1.add(actor40);

		obj1.add(actor41);
		obj1.add(actor42);
		obj1.add(actor43);
		obj1.add(actor44);
		obj1.add(actor45);
		obj1.add(actor46);
		obj1.add(actor47);
		obj1.add(actor48);
		obj1.add(actor49);
		obj1.add(actor50);

		obj1.add(actor51);
		obj1.add(actor52);
		obj1.add(actor53);
		obj1.add(actor54);
		obj1.add(actor55);
		obj1.add(actor56);
		obj1.add(actor57);
		obj1.add(actor58);
		obj1.add(actor59);
		obj1.add(actor60);
		
		System.out.println(actor1);
		System.out.println(actor2);
		System.out.println(actor3);
		System.out.println(actor4);
		System.out.println(actor5);
		System.out.println(actor6);
		System.out.println(actor7);
		System.out.println(actor8);
		System.out.println(actor9);
		System.out.println(actor10);
		
		System.out.println(actor11);
		System.out.println(actor12);
		System.out.println(actor13);
		System.out.println(actor14);
		System.out.println(actor15);
		System.out.println(actor16);
		System.out.println(actor17);
		System.out.println(actor18);
		System.out.println(actor19);
		System.out.println(actor20);
		
		System.out.println(actor21);
		System.out.println(actor22);
		System.out.println(actor23);
		System.out.println(actor24);
		System.out.println(actor25);
		System.out.println(actor26);
		System.out.println(actor27);
		System.out.println(actor28);
		System.out.println(actor29);
		System.out.println(actor30);
		
		System.out.println(actor31);
		System.out.println(actor32);
		System.out.println(actor33);
		System.out.println(actor34);
		System.out.println(actor35);
		System.out.println(actor36);
		System.out.println(actor37);
		System.out.println(actor38);
		System.out.println(actor39);
		System.out.println(actor40);
		
		System.out.println(actor41);
		System.out.println(actor42);
		System.out.println(actor43);
		System.out.println(actor44);
		System.out.println(actor45);
		System.out.println(actor46);
		System.out.println(actor47);
		System.out.println(actor48);
		System.out.println(actor49);
		System.out.println(actor50);
		
		System.out.println(actor51);
		System.out.println(actor52);
		System.out.println(actor53);
		System.out.println(actor54);
		System.out.println(actor55);
		System.out.println(actor56);
		System.out.println(actor57);
		System.out.println(actor58);
		System.out.println(actor59);
		System.out.println(actor60);
		System.out.println();
		
		
		
		
		
		System.out.println();

		System.out.println("Languages");
		System.out.println("------------------");
		
		String lang1="Hindi";
		String lang2="Bengali";
		String lang3="Marathi";
		String lang4="Telugu";
		String lang5="Tamil";
		String lang6="Gujarati";
		String lang7="Urdu";
		String lang8="Kannada";
		String lang9="Odia";
		String lang10="Malayalam";
		String lang11="Punjabi";
		String lang12="Bodo";
		String lang13="Dogri";
		String lang14="Kashmiri";
		String lang15="Konkani";
		String lang16="Maithili";
		String lang17="Manipuri";
		String lang18="Nepali";
		String lang19="Sanskrit";
		String lang20="Santali Language";
		String lang21="Sindhi";
		String lang22="Assamese";
		String lang23="	Chinese";
		String lang24="	Spanish";
		String lang25="	Arabic";
		String lang26="	Russian";
		String lang27="	Portuguese";
		String lang28="	Telugu";
		String lang29="	Tamil";
		String lang30="	Italian";
		String lang31="German, Standard";
		String lang32="Javanese";
		String lang33="	Lahnda";
		String lang34="	Marathi";
		String lang35="	French";
		String lang36="	Korean";
		String lang37="Indonesia";
		String lang38="Turkish";
		String lang39="Indo-European";
		String lang40="Afro-Asiatic ";
		String lang41="Niger-Congo";
		String lang42="Sino-Tibetan";
		String lang43="Austronesian";
		String lang44="Dravidian";
		String lang45="Kra-Dai";
		String lang46="Koreanic";
		String lang47="Vietnamese";
		String lang48="Niger-Saharian";
		String lang49="Khoisan";
		String lang50="Afro-Asiatic";
		String lang51="Nilo-Saharian";
		String lang52="Bahrain";
		String lang53="Cyprus";
		String lang54="Georgia";
		String lang55="Israel";
		String lang56="Kuwait";
		String lang57="Laos";
		String lang58="Malaysia";
		String lang59="Maldivian Dhivehi";
		String lang60="	Arabic ";
		
		Collection obj2 = new ArrayList();
		obj2.add(lang1);
		obj2.add(lang2);
		obj2.add(lang3);
		obj2.add(lang4);
		obj2.add(lang5);
		obj2.add(lang6);
		obj2.add(lang7);
		obj2.add(lang8);
		obj2.add(lang9);
		obj2.add(lang10);
		obj2.add(lang11);
		obj2.add(lang12);
		obj2.add(lang13);
		obj2.add(lang14);
		obj2.add(lang15);
		obj2.add(lang16);
		obj2.add(lang17);
		obj2.add(lang18);
		obj2.add(lang19);
		obj2.add(lang20);
		obj2.add(lang21);
		obj2.add(lang22);
		obj2.add(lang23);
		obj2.add(lang24);
		obj2.add(lang25);
		obj2.add(lang26);
		obj2.add(lang27);
		obj2.add(lang28);
		obj2.add(lang29);
		obj2.add(lang30);
		obj2.add(lang31);
		obj2.add(lang32);
		obj2.add(lang33);
		obj2.add(lang34);
		obj2.add(lang35);
		obj2.add(lang36);
		obj2.add(lang37);
		obj2.add(lang38);
		obj2.add(lang39);
		obj2.add(lang40);
		obj2.add(lang41);
		obj2.add(lang42);
		obj2.add(lang43);
		obj2.add(lang44);
		obj2.add(lang45);
		obj2.add(lang46);
		obj2.add(lang47);
		obj2.add(lang48);
		obj2.add(lang49);
		obj2.add(lang50);
		obj2.add(lang51);
		obj2.add(lang52);
		obj2.add(lang53);
		obj2.add(lang54);
		obj2.add(lang55);
		obj2.add(lang56);
		obj2.add(lang57);
		obj2.add(lang58);
		obj2.add(lang59);
		obj2.add(lang60);
		
		
		System.out.println(lang1);
		System.out.println(lang2);
		System.out.println(lang3);
		System.out.println(lang4);
		System.out.println(lang5);
		System.out.println(lang6);
		System.out.println(lang7);
		System.out.println(lang8);
		System.out.println(lang9);
		System.out.println(lang10);
		
		System.out.println(lang11);
		System.out.println(lang12);
		System.out.println(lang13);
		System.out.println(lang14);
		System.out.println(lang15);
		System.out.println(lang16);
		System.out.println(lang17);
		System.out.println(lang18);
		System.out.println(lang19);
		System.out.println(lang20);
		
		System.out.println(lang21);
		System.out.println(lang22);
		System.out.println(lang23);
		System.out.println(lang24);
		System.out.println(lang25);
		System.out.println(lang26);
		System.out.println(lang27);
		System.out.println(lang28);
		System.out.println(lang29);
		System.out.println(lang30);
		
		System.out.println(lang31);
		System.out.println(lang32);
		System.out.println(lang33);
		System.out.println(lang34);
		System.out.println(lang35);
		System.out.println(lang36);
		System.out.println(lang37);
		System.out.println(lang38);
		System.out.println(lang39);
		System.out.println(lang40);
		
		System.out.println(lang41);
		System.out.println(lang42);
		System.out.println(lang43);
		System.out.println(lang44);
		System.out.println(lang45);
		System.out.println(lang46);
		System.out.println(lang47);
		System.out.println(lang48);
		System.out.println(lang49);
		System.out.println(lang50);
		
		System.out.println(lang51);
		System.out.println(lang52);
		System.out.println(lang53);
		System.out.println(lang54);
		System.out.println(lang55);
		System.out.println(lang56);
		System.out.println(lang57);
		System.out.println(lang58);
		System.out.println(lang59);
		System.out.println(lang60);
		System.out.println();
		
		
		
		System.out.println("Movies");
		System.out.println("------------------");
		String moviename1="Dear Zindagi";
		String moviename2=" Raazi ";
		String moviename3="Udta Punjab";
		String moviename4=" Highway";
		String moviename5=" Gully Boy";
		String moviename6="2 States";
		String moviename7="Kapoor & Sons";
		String moviename8="Badrinath Ki Dulhania ";
		String moviename9="Humpty Sharma Ki Dulhania";
		String moviename10="Student of the Year";
		
		String moviename11="Chhichhore";
		String moviename12="Stree";
		String moviename13="The Villain";
		String moviename14="OK Jaanu";
		String moviename15="Saaho ";
		String moviename16=" Any Body Can Dance 2";
		String moviename17="Baaghi";
		String moviename18="Arya";
		String moviename19="Arya 2";
		String moviename20="Race Gurram";
		
		String moviename21=" Julayi ";
		String moviename22="Ala Vaikunthapurramuloo";
		String moviename23="Happy";
		String moviename24=" S/O Satyamurthy";
		String moviename25="Sarrainodu";
		String moviename26=" Iddarammayilatho";
		String moviename27="Yevadu";
		String moviename28="Badrinath ";
		String moviename29="Magadheera";
		String moviename30="Thuppakki ";
		
		String moviename31="Darling";
		String moviename32="Brindaavanam";
		String moviename33="Mr Perfect ";
		String moviename34="Singham";
		String moviename35="The Godfather";
		String moviename36="Jalebi";
		String moviename37="L7 ";
		String moviename38="Sardar Udham";
		String moviename39="Shershaah ";
		String moviename40="Mimi";
		
		String moviename41="Flight";
		String moviename42="Dhamaka";
		String moviename43="K.G.F. Chapter 2";
		String moviename44="James";
		String moviename45="The King's Speech";
		String moviename46="Forrest Gump";
		String moviename47="The Matrix";
		String moviename48="Inception ";
		String moviename49="The Dark Knight ";
		String moviename50="The Dark Knight Rises";
		
		String moviename51="The Aviator ";
		String moviename52="WALL·E ";
		String moviename53="Let the Right One In";
		String moviename54="The Conjuring";
		String moviename55="Pitch Black ";
		String moviename56="The Witch";
		String moviename57=" The Descent ";
		String moviename58="Insidious ";
		String moviename59="The Hills Have Eyes";
		String moviename60="Noroi";
		
		Collection obj3 = new ArrayList();
		obj3.add(moviename1);
		obj3.add(moviename2);
		obj3.add(moviename3);
		obj3.add(moviename4);
		obj3.add(moviename5);
		obj3.add(moviename6);
		obj3.add(moviename7);
		obj3.add(moviename8);
		obj3.add(moviename9);
		obj3.add(moviename10);
		obj3.add(moviename11);
		obj3.add(moviename12);
		obj3.add(moviename13);
		obj3.add(moviename14);
		obj3.add(moviename15);
		obj3.add(moviename16);
		obj3.add(moviename17);
		obj3.add(moviename18);
		obj3.add(moviename19);
		obj3.add(moviename20);
		obj3.add(moviename21);
		obj3.add(moviename22);
		obj3.add(moviename23);
		obj3.add(moviename24);
		obj3.add(moviename25);
		obj3.add(moviename26);
		obj3.add(moviename27);
		obj3.add(moviename28);
		obj3.add(moviename29);
		obj3.add(moviename30);
		
		obj3.add(moviename31);
		obj3.add(moviename32);
		obj3.add(moviename33);
		obj3.add(moviename34);
		obj3.add(moviename35);
		obj3.add(moviename36);
		obj3.add(moviename37);
		obj3.add(moviename38);
		obj3.add(moviename39);
		obj3.add(moviename40);
		
		obj3.add(moviename41);
		obj3.add(moviename42);
		obj3.add(moviename43);
		obj3.add(moviename44);
		obj3.add(moviename45);
		obj3.add(moviename46);
		obj3.add(moviename47);
		obj3.add(moviename48);
		obj3.add(moviename49);
		obj3.add(moviename50);
		
		obj3.add(moviename51);
		obj3.add(moviename52);
		obj3.add(moviename53);
		obj3.add(moviename54);
		obj3.add(moviename55);
		obj3.add(moviename56);
		obj3.add(moviename57);
		obj3.add(moviename58);
		obj3.add(moviename59);
		obj3.add(moviename60);
		
		
		System.out.println(moviename1);
		System.out.println(moviename2);
		System.out.println(moviename3);
		System.out.println(moviename4);
		System.out.println(moviename5);
		System.out.println(moviename6);
		System.out.println(moviename7);
		System.out.println(moviename8);
		System.out.println(moviename9);
		System.out.println(moviename10);
		
		System.out.println(moviename11);
		System.out.println(moviename12);
		System.out.println(moviename13);
		System.out.println(moviename14);
		System.out.println(moviename15);
		System.out.println(moviename16);
		System.out.println(moviename17);
		System.out.println(moviename18);
		System.out.println(moviename19);
		System.out.println(moviename20);
		
		System.out.println(moviename21);
		System.out.println(moviename22);
		System.out.println(moviename23);
		System.out.println(moviename24);
		System.out.println(moviename25);
		System.out.println(moviename26);
		System.out.println(moviename27);
		System.out.println(moviename28);
		System.out.println(moviename29);
		System.out.println(moviename30);
		
		System.out.println(moviename31);
		System.out.println(moviename32);
		System.out.println(moviename33);
		System.out.println(moviename34);
		System.out.println(moviename35);
		System.out.println(moviename36);
		System.out.println(moviename37);
		System.out.println(moviename38);
		System.out.println(moviename39);
		System.out.println(moviename40);
		
		System.out.println(moviename41);
		System.out.println(moviename42);
		System.out.println(moviename43);
		System.out.println(moviename44);
		System.out.println(moviename45);
		System.out.println(moviename46);
		System.out.println(moviename47);
		System.out.println(moviename48);
		System.out.println(moviename49);
		System.out.println(moviename50);
		
		System.out.println(moviename51);
		System.out.println(moviename52);
		System.out.println(moviename53);
		System.out.println(moviename54);
		System.out.println(moviename55);
		System.out.println(moviename56);
		System.out.println(moviename57);
		System.out.println(moviename58);
		System.out.println(moviename59);
		System.out.println(moviename60);
		System.out.println();
		
		System.out.println("web series");
		System.out.println("------------------");
		
		String webseries1="Sacred Games";
		String webseries2="Mirzapur";
		String webseries3="Asur";
		String webseries4="special OPS";
		String webseries5="Inside Edge ";
		String webseries6="Undekhi";
		String webseries7="Panchayat";
		String webseries8="Avrodh";
		String webseries9=" Mafia";
		String webseries10="The Family Man";
		String webseries11="Jamtara";
		String webseries12="Delhi Crime";
		String webseries13="Selection Day ";
		String webseries14="Paatal Lok";
		String webseries15="Breathe";
		String webseries16="Breathe: Into the Shadows";
		String webseries17=" Bhaukaal";
		String webseries18="Samantar ";
		String webseries19="The Verdict - State Vs Nanavati";
		String webseries20="Apharan";
		
		String webseries21="Fittrat ";
		String webseries22="Criminal Justice";
		String webseries23="Aarya";
		String webseries24="Lalbazaar";
		String webseries25="State of Siege: 26/11 ";
		String webseries26="Rangbaaz ";
		String webseries27="Hostel Daze";
		String webseries28="Kota Factory ";
		String webseries29="Yeh Meri Family";
		String webseries30="TVF Pitchers ";
		
		String webseries31="TVF Tripling";
		String webseries32="Permanent Roommates";
		String webseries33="Titans Season 3";
		String webseries34="Inside Edge Season 3";
		String webseries35="Lost in Space Season 3";
		String webseries36="Hawkeye";
		String webseries37="Cowboy Bebop Season 1";
		String webseries38="The Wheel of Time";
		String webseries39="Star Trek: Discovery Season 4";
		String webseries40="Special Ops 1.5";
		
		String webseries41="Call My Agent: Bollywood";
		String webseries42="Succession Season 3";
		String webseries43="Little Things Season 4";
		String webseries44="House of Secrets: The Burari Deaths";
		String webseries45="Break Point";
		String webseries46="Foundation Season 1";
		String webseries47="Kota Factory Season 2";
		String webseries48="Star Wars: Visions Season 1";
		String webseries49="Mumbai Diaries 26/11";
		String webseries50="The Empire Season 1";
		
		String webseries51="Ray Season 1";
		String webseries52="The Family Man Season 2";
		String webseries53="Never Have I Ever Season 2";
		String webseries54="Ted Lasso Season 2";
		String webseries55="Money Heist Season 5";
		String webseries56="The Empire Season 1";
		String webseries57="Foundation Season 1";
		String webseries58="Kota Factory Season 2";
		String webseries59="Squid Game Season 1";
		String webseries60="Mumbai Diaries 26/11";
		
		Collection obj4= new ArrayList();
		obj4.add(webseries1);
		obj4.add(webseries2);
		obj4.add(webseries3);
		obj4.add(webseries4);
		obj4.add(webseries5);
		obj4.add(webseries6);
		obj4.add(webseries7);
		obj4.add(webseries8);
		obj4.add(webseries9);
		obj4.add(webseries10);
		obj4.add(webseries11);
		obj4.add(webseries12);
		obj4.add(webseries13);
		obj4.add(webseries14);
		obj4.add(webseries15);
		obj4.add(webseries16);
		obj4.add(webseries17);
		obj4.add(webseries18);
		obj4.add(webseries19);
		obj4.add(webseries20);
		obj4.add(webseries21);
		obj4.add(webseries22);
		obj4.add(webseries23);
		obj4.add(webseries24);
		obj4.add(webseries25);
		obj4.add(webseries26);
		obj4.add(webseries27);
		obj4.add(webseries28);
		obj4.add(webseries29);
		obj4.add(webseries30);
		obj4.add(webseries31);
		obj4.add(webseries32);
		obj4.add(webseries33);
		obj4.add(webseries34);
		obj4.add(webseries35);
		obj4.add(webseries36);
		obj4.add(webseries37);
		obj4.add(webseries38);
		obj4.add(webseries39);
		obj4.add(webseries40);
		obj4.add(webseries41);
		obj4.add(webseries42);
		obj4.add(webseries43);
		obj4.add(webseries44);
		obj4.add(webseries45);
		obj4.add(webseries46);
		obj4.add(webseries47);
		obj4.add(webseries48);
		obj4.add(webseries49);
		obj4.add(webseries50);
		obj4.add(webseries51);
		obj4.add(webseries52);
		obj4.add(webseries53);
		obj4.add(webseries54);
		obj4.add(webseries55);
		obj4.add(webseries56);
		obj4.add(webseries57);
		obj4.add(webseries58);
		obj4.add(webseries59);
		obj4.add(webseries60);
		
		
		System.out.println(webseries1);
		System.out.println(webseries2);
		System.out.println(webseries3);
		System.out.println(webseries4);
		System.out.println(webseries5);
		System.out.println(webseries6);
		System.out.println(webseries7);
		System.out.println(webseries8);
		System.out.println(webseries9);
		System.out.println(webseries10);
		
		System.out.println(webseries11);
		System.out.println(webseries12);
		System.out.println(webseries13);
		System.out.println(webseries14);
		System.out.println(webseries15);
		System.out.println(webseries16);
		System.out.println(webseries17);
		System.out.println(webseries18);
		System.out.println(webseries19);
		System.out.println(webseries20);
		
		System.out.println(webseries21);
		System.out.println(webseries22);
		System.out.println(webseries23);
		System.out.println(webseries24);
		System.out.println(webseries25);
		System.out.println(webseries26);
		System.out.println(webseries27);
		System.out.println(webseries28);
		System.out.println(webseries29);
		System.out.println(webseries30);
		
		System.out.println(webseries31);
		System.out.println(webseries32);
		System.out.println(webseries33);
		System.out.println(webseries34);
		System.out.println(webseries35);
		System.out.println(webseries36);
		System.out.println(webseries37);
		System.out.println(webseries38);
		System.out.println(webseries39);
		System.out.println(webseries40);
		
		System.out.println(webseries41);
		System.out.println(webseries42);
		System.out.println(webseries43);
		System.out.println(webseries44);
		System.out.println(webseries45);
		System.out.println(webseries46);
		System.out.println(webseries47);
		System.out.println(webseries48);
		System.out.println(webseries49);
		System.out.println(webseries50);
		
		System.out.println(webseries51);
		System.out.println(webseries52);
		System.out.println(webseries53);
		System.out.println(webseries54);
		System.out.println(webseries55);
		System.out.println(webseries56);
		System.out.println(webseries57);
		System.out.println(webseries58);
		System.out.println(webseries59);
		System.out.println(webseries60);
		System.out.println();
		
		
		System.out.println("cities");
		System.out.println("------------------");
		
		String city1="Mumbai";
		String city2="Delhi";
		String city3="Bangalore";
		String city4="Hyderabad";
		String city5="Ahmedabad";
		String city6="Chennai";
		String city7="Kolkata";
		String city8="Surat";
		String city9="Pune";
		String city10="Jaipur";
		
		String city11="Lucknow";
		String city12="Kanpur";
		String city13="Nagpur";
		String city14="Indore";
		String city15="Thane";
		String city16="Bhopal";
		String city17="Visakhapatnam";
		String city18="Pimpri-Chinchwad";
		String city19="Patna";
		String city20="Vadodara";
		
		String city21="Ghaziabad";
		String city22="Ludhiana";
		String city23="Agra";
		String city24="Coimbatore";
		String city25="Nashik";
		String city26="Ranchi";
		String city27="Faridabad";
		String city28="Meerut";
		String city29="Rajkot";
		String city30="Kalyan-Dombivli";
		
		String city31="Vasai-Virar";
		String city32="Varanasi";
		String city33="Srinagar";
		String city34="Aurangabad";
		String city35="Dhanbad";
		String city36="Gurgaon";
		String city37="Amritsar";
		String city38="Navi Mumbai";
		String city39="Allahabad";
		String city40="Howrah";
		
		String city41="Gwalior";
		String city42="Jabalpur";
		String city43="Vijayawada";
		String city44="Jodhpur";
		String city45="Salem";
		String city46="Madurai";
		String city47="Raipur";
		String city48="Chandigarh";
		String city49="Guwahati";
		String city50="Solapur";
		
		String city51="Hubli–Dharwad";
		String city52="Aligarh";
		String city53="Tiruppur";
		String city54="Jalandhar";
		String city55="Bhiwandi";
		String city56="Bikaner";
		String city57="Noida";
		String city58="Kochi";
		String city59="Bhavnagar";
		String city60="Gulbarga";
		
		Collection obj5= new ArrayList();
		obj5.add(city1);
		obj5.add(city2);
		obj5.add(city3);
		obj5.add(city4);
		obj5.add(city5);
		obj5.add(city6);
		obj5.add(city7);
		obj5.add(city8);
		obj5.add(city9);
		obj5.add(city10);
		
		obj5.add(city11);
		obj5.add(city12);
		obj5.add(city13);
		obj5.add(city14);
		obj5.add(city15);
		obj5.add(city16);
		obj5.add(city17);
		obj5.add(city18);
		obj5.add(city19);
		obj5.add(city20);
		
		obj5.add(city21);
		obj5.add(city22);
		obj5.add(city23);
		obj5.add(city24);
		obj5.add(city25);
		obj5.add(city26);
		obj5.add(city27);
		obj5.add(city28);
		obj5.add(city29);
		obj5.add(city30);
		
		obj5.add(city31);
		obj5.add(city32);
		obj5.add(city33);
		obj5.add(city34);
		obj5.add(city35);
		obj5.add(city36);
		obj5.add(city37);
		obj5.add(city38);
		obj5.add(city39);
		obj5.add(city40);
		
		obj5.add(city41);
		obj5.add(city42);
		obj5.add(city43);
		obj5.add(city44);
		obj5.add(city45);
		obj5.add(city46);
		obj5.add(city47);
		obj5.add(city48);
		obj5.add(city49);
		obj5.add(city50);
		
		obj5.add(city51);
		obj5.add(city52);
		obj5.add(city53);
		obj5.add(city54);
		obj5.add(city55);
		obj5.add(city56);
		obj5.add(city57);
		obj5.add(city58);
		obj5.add(city59);
		obj5.add(city60);
		
		
		System.out.println(city1);
		System.out.println(city2);
		System.out.println(city3);
		System.out.println(city4);
		System.out.println(city5);
		System.out.println(city6);
		System.out.println(city7);
		System.out.println(city8);
		System.out.println(city9);
		System.out.println(city10);
		
		System.out.println(city11);
		System.out.println(city12);
		System.out.println(city13);
		System.out.println(city14);
		System.out.println(city15);
		System.out.println(city16);
		System.out.println(city17);
		System.out.println(city18);
		System.out.println(city19);
		System.out.println(city20);
		
		System.out.println(city21);
		System.out.println(city22);
		System.out.println(city23);
		System.out.println(city24);
		System.out.println(city25);
		System.out.println(city26);
		System.out.println(city27);
		System.out.println(city28);
		System.out.println(city29);
		System.out.println(city30);
		
		System.out.println(city31);
		System.out.println(city32);
		System.out.println(city33);
		System.out.println(city34);
		System.out.println(city35);
		System.out.println(city36);
		System.out.println(city37);
		System.out.println(city38);
		System.out.println(city39);
		System.out.println(city40);
		
		System.out.println(city41);
		System.out.println(city42);
		System.out.println(city43);
		System.out.println(city44);
		System.out.println(city45);
		System.out.println(city46);
		System.out.println(city47);
		System.out.println(city48);
		System.out.println(city49);
		System.out.println(city50);
		
		System.out.println(city51);
		System.out.println(city52);
		System.out.println(city53);
		System.out.println(city54);
		System.out.println(city55);
		System.out.println(city56);
		System.out.println(city57);
		System.out.println(city58);
		System.out.println(city59);
		System.out.println(city60);
		System.out.println();
		
		
		System.out.println("sweets");
		System.out.println("-----------------");
		
		String sweet1=" Ras Malai";
		String sweet2="Gajar Ka Halwa";
		String sweet3="Gulab jamun";
		String sweet4="Kheer";
		String sweet5="Kulfi";
		String sweet6="Rabri";
		String sweet7="Rasgulla";
		String sweet8=" Jalebi";
		String sweet9="Gujia";
		String sweet10="Bal Mithai";
		
		String sweet11="Son Papri";
		String sweet12="Sandesh";
		String sweet13="Shrikhand";
		String sweet14="Suzi Halva";
		String sweet15="Kaju Katli";
		String sweet16="Modak";
		String sweet17="Malpua";
		String sweet18="Chirote";
		String sweet19="Shrikhand";
		String sweet20="Basundi";
		
		String sweet21="Amrakhand";
		String sweet22="Strawberry Roshogullah";
		String sweet23="Kiwi Roshogullah";
		String sweet24="Chilli Roshogullah";
		String sweet25="Blueberry Roshogullah";
		String sweet26="Watermelon Roshogullah";
		String sweet27="Coconut Rose Roshogullah";
		String sweet28="Butterscotch Roshogullah";
		String sweet29="Kala Khatta Roshogullah";
		String sweet30="Green Apple Roshogullah";
		
		String sweet31="Pineapple Roshogullah";
		String sweet32="Chavde";
		String sweet33="Karanji";
		String sweet34="Aamras";
		String sweet35="Basundi";
		String sweet36="Shrikhand";
		String sweet37="Moosbeernocken";
		String sweet38="Prügeltorte";
		String sweet39="Strauben";
		String sweet40="Jhajariya";
		
		String sweet41="Ghevar";
		String sweet42="Boondi";
		String sweet43="Churma";
		String sweet44="Canestrelli di Avosso";
		String sweet45="Rotelle di Borzonasca";
		String sweet46="Biscotti del Lagaccio";
		String sweet47="Sacripantina";
		String sweet48="Sacripantina";
		String sweet49="Pandolce";
		String sweet50="Chocolate Fish";
		
		String sweet51="Dolly Varden";
		String sweet52="Getuk";
		String sweet53="Kue putu";
		String sweet54="Dadar gulung";
		String sweet55="Pisang goreng";
		String sweet56="Maccheroni con le noci";
		String sweet57="Brustengolo";
		String sweet58="Pampepato di Terni";
		String sweet59="Crescionda";
		String sweet60="Rocciata";
		
		Collection obj6= new ArrayList();
		obj6.add(sweet1);
		obj6.add(sweet2);
		obj6.add(sweet3);
		obj6.add(sweet4);
		obj6.add(sweet5);
		obj6.add(sweet6);
		obj6.add(sweet7);
		obj6.add(sweet8);
		obj6.add(sweet9);
		obj6.add(sweet10);
		
		obj6.add(sweet11);
		obj6.add(sweet12);
		obj6.add(sweet13);
		obj6.add(sweet14);
		obj6.add(sweet15);
		obj6.add(sweet16);
		obj6.add(sweet17);
		obj6.add(sweet18);
		obj6.add(sweet19);
		obj6.add(sweet20);
		
		obj6.add(sweet21);
		obj6.add(sweet22);
		obj6.add(sweet23);
		obj6.add(sweet24);
		obj6.add(sweet25);
		obj6.add(sweet26);
		obj6.add(sweet27);
		obj6.add(sweet28);
		obj6.add(sweet29);
		obj6.add(sweet30);
		
		obj6.add(sweet31);
		obj6.add(sweet32);
		obj6.add(sweet33);
		obj6.add(sweet34);
		obj6.add(sweet35);
		obj6.add(sweet36);
		obj6.add(sweet37);
		obj6.add(sweet38);
		obj6.add(sweet39);
		obj6.add(sweet40);
		
		obj6.add(sweet41);
		obj6.add(sweet42);
		obj6.add(sweet43);
		obj6.add(sweet44);
		obj6.add(sweet45);
		obj6.add(sweet46);
		obj6.add(sweet47);
		obj6.add(sweet48);
		obj6.add(sweet49);
		obj6.add(sweet50);
		
		obj6.add(sweet51);
		obj6.add(sweet52);
		obj6.add(sweet53);
		obj6.add(sweet54);
		obj6.add(sweet55);
		obj6.add(sweet56);
		obj6.add(sweet57);
		obj6.add(sweet58);
		obj6.add(sweet59);
		obj6.add(sweet60);
		
		
		
		System.out.println(sweet1);
		System.out.println(sweet2);
		System.out.println(sweet3);
		System.out.println(sweet4);
		System.out.println(sweet5);
		System.out.println(sweet6);
		System.out.println(sweet7);
		System.out.println(sweet8);
		System.out.println(sweet9);
		System.out.println(sweet10);
		
		System.out.println(sweet11);
		System.out.println(sweet12);
		System.out.println(sweet13);
		System.out.println(sweet14);
		System.out.println(sweet15);
		System.out.println(sweet16);
		System.out.println(sweet17);
		System.out.println(sweet18);
		System.out.println(sweet19);
		System.out.println(sweet20);
		
		System.out.println(sweet21);
		System.out.println(sweet22);
		System.out.println(sweet23);
		System.out.println(sweet24);
		System.out.println(sweet25);
		System.out.println(sweet26);
		System.out.println(sweet27);
		System.out.println(sweet28);
		System.out.println(sweet29);
		System.out.println(sweet30);
		
		System.out.println(sweet31);
		System.out.println(sweet32);
		System.out.println(sweet33);
		System.out.println(sweet34);
		System.out.println(sweet35);
		System.out.println(sweet36);
		System.out.println(sweet37);
		System.out.println(sweet38);
		System.out.println(sweet39);
		System.out.println(sweet40);
		
		System.out.println(sweet51);
		System.out.println(sweet52);
		System.out.println(sweet53);
		System.out.println(sweet54);
		System.out.println(sweet55);
		System.out.println(sweet56);
		System.out.println(sweet57);
		System.out.println(sweet58);
		System.out.println(sweet59);
		System.out.println(sweet60);
		System.out.println();
		
		
		System.out.println("bikes");
		System.out.println("-----------------");
		
		String bike1="Royal Enfield Classic";
		String bike2="TVS Jupiter 125";
		String bike3="TVS Apache RTR 160";
		String bike4="Yamaha YZF R15 V3";
		String bike5="TVS Apache RTR";
		String bike6="Yamaha MT";
		String bike7="TVS Jupiter";
		String bike8="Hero Splendor Plus";
		String bike9="TVS Sport";
		String bike10="Alan Bike";
		
		String bike11="Altruiste Bikes";
		String bike12="Argon 18";
		String bike13="Ascari";
		String bike14="Centy Karizma Bike";
		String bike15="NEXOVA";
		String bike16="Parteet";
		String bike17="TVS iQube Electric";
		String bike18="Yamaha YZF R15 V3";
		String bike19="TVS Apache RTR 200 4V";
		String bike20="TVS Apache RTR 200 4V";
		
		String bike21="Bajaj Pulsar 150";
		String bike22="JAWA Forty Two";
		String bike23="Royal Enfield Bullet 350";
		String bike24="Suzuki Intruder";
		String bike25="Suzuki Intruder";
		String bike26="Honda CB Shine";
		String bike27="Honda Activa 6G";
		String bike28="Honda Dio";
		String bike29="Hero Splendor Plus";
		String bike30="Bajaj Pulsar 125";
		
		String bike31="Honda CB Unicorn 160";
		String bike32="Hero Electric Optima HX";
		String bike33="Bajaj Pulsar 150";
		String bike34="Suzuki Intruder";
		String bike35="Argon 18";
		String bike36="NEXOVA";
		String bike37="Parteet";
		String bike38="TVS Apache RTR 200 4V";
		String bike39="Bajaj Pulsar 150";
		String bike40="Hero Splendor Plus";
		
		String bike41="Royal Enfield Classic";
		String bike42="Ascari";
		String bike43="Bajaj Pulsar 150";
		String bike44="Parteet";
		String bike45="Honda Dio";
		String bike46="Argon 18";
		String bike47="Honda Activa 6G";
		String bike48="Argon 18";
		String bike49="Suzuki Intruder";
		String bike50="bajaj Pulsar 150";
		
		String bike51="Royal Enfield Classic";
		String bike52="TVS Jupiter 125";
		String bike53="TVS Apache RTR 160";
		String bike54="Yamaha YZF R15 V3";
		String bike55="TVS Apache RTR";
		String bike56="Yamaha MT";
		String bike57="TVS Jupiter";
		String bike58="Hero Splendor Plus";
		String bike59="TVS Sport";
		String bike60="Alan Bike";
		System.out.println();
		
		Collection obj7= new ArrayList();
		obj7.add(bike1);
		obj7.add(bike2);
		obj7.add(bike3);
		obj7.add(bike4);
		obj7.add(bike5);
		obj7.add(bike6);
		obj7.add(bike7);
		obj7.add(bike8);
		obj7.add(bike9);
		obj7.add(bike10);
		
		obj7.add(bike11);
		obj7.add(bike12);
		obj7.add(bike13);
		obj7.add(bike14);
		obj7.add(bike15);
		obj7.add(bike16);
		obj7.add(bike17);
		obj7.add(bike18);
		obj7.add(bike19);
		obj7.add(bike20);
		
		obj7.add(bike21);
		obj7.add(bike22);
		obj7.add(bike23);
		obj7.add(bike24);
		obj7.add(bike25);
		obj7.add(bike26);
		obj7.add(bike27);
		obj7.add(bike28);
		obj7.add(bike29);
		obj7.add(bike30);
		
		obj7.add(bike31);
		obj7.add(bike32);
		obj7.add(bike33);
		obj7.add(bike34);
		obj7.add(bike35);
		obj7.add(bike36);
		obj7.add(bike37);
		obj7.add(bike38);
		obj7.add(bike39);
		obj7.add(bike40);
		
		obj7.add(bike41);
		obj7.add(bike42);
		obj7.add(bike43);
		obj7.add(bike44);
		obj7.add(bike45);
		obj7.add(bike46);
		obj7.add(bike47);
		obj7.add(bike48);
		obj7.add(bike49);
		obj7.add(bike50);
		
		obj7.add(bike51);
		obj7.add(bike52);
		obj7.add(bike53);
		obj7.add(bike54);
		obj7.add(bike55);
		obj7.add(bike56);
		obj7.add(bike57);
		obj7.add(bike58);
		obj7.add(bike59);
		obj7.add(bike60);
		
		
		System.out.println(bike1);
		System.out.println(bike2);
		System.out.println(bike3);
		System.out.println(bike4);
		System.out.println(bike5);
		System.out.println(bike6);
		System.out.println(bike7);
		System.out.println(bike8);
		System.out.println(bike9);
		System.out.println(bike10);
		
		System.out.println(bike11);
		System.out.println(bike12);
		System.out.println(bike13);
		System.out.println(bike14);
		System.out.println(bike15);
		System.out.println(bike16);
		System.out.println(bike17);
		System.out.println(bike18);
		System.out.println(bike19);
		System.out.println(bike20);
		
		System.out.println(bike21);
		System.out.println(bike22);
		System.out.println(bike23);
		System.out.println(bike24);
		System.out.println(bike25);
		System.out.println(bike26);
		System.out.println(bike27);
		System.out.println(bike28);
		System.out.println(bike29);
		System.out.println(bike30);
		
		System.out.println(bike31);
		System.out.println(bike32);
		System.out.println(bike33);
		System.out.println(bike34);
		System.out.println(bike35);
		System.out.println(bike36);
		System.out.println(bike37);
		System.out.println(bike38);
		System.out.println(bike39);
		System.out.println(bike40);
		
		System.out.println(bike41);
		System.out.println(bike42);
		System.out.println(bike43);
		System.out.println(bike44);
		System.out.println(bike45);
		System.out.println(bike46);
		System.out.println(bike47);
		System.out.println(bike48);
		System.out.println(bike49);
		System.out.println(bike50);
		
		System.out.println(bike51);
		System.out.println(bike52);
		System.out.println(bike53);
		System.out.println(bike54);
		System.out.println(bike55);
		System.out.println(bike56);
		System.out.println(bike57);
		System.out.println(bike58);
		System.out.println(bike59);
		System.out.println(bike60);
		System.out.println();
		
		
		System.out.println("cars");
		System.out.println("-----------------");
		 String car1="Audi";
		 String car2="BMW";
		 String car3="BMW M";
		 String car4="Creta";
		 String car5="elantra";
		 String car6="fortuner";
		 String car7="suzuki celerio";
		 String car8="hyundai i10";
		 String car9="maruti suzuki";
		 String car10="amaze";
		 
		 String car11="astar";
		 String car12="ertiga";
		 String car13="mahindra scorpio";
		 String car14=" ford everest";
		 String car15=" toyota";
		 String car16="mahindra xuv500";
		 String car17="porsche";
		 String car18="mitsubishi";
		 String car19="tata nexon";
		 String car20=" swift";
		 
		 String car21="lamborghini";
		 String car22="lexus";
		 String car23="ferrari";
		 String car24="land rover";
		 String car25="kia seltos";
		 String car26="tata harrier";
		 String car27="toyota fortuner";
		 String car28="chevrolet";
		 String car29="bently";
		 String car30="jaguar";
		 
		 String car31="volkswagen";
		 String car32="ford";
		 String car33="honda";
		 String car34="mercedes benz";
		 String car35="porsche";
		 String car36="audi Q5";
		 String car37="mercedes benz AMG A45 S";
		 String car38="BYD E6";
		 String car39=" Volvo S90";
		 String car40="Tata punch";
		 
		 String car41="MG Astor";
		 String car42="Force motors gurkha";
		 String car43="ferrari";
		 String car44="ford";
		 String car45="audi Q5";
		 String car46="lamborghini";
		 String car47="porsche";
		 String car48="Volvo S90";
		 String car49="Tata punch";
		 String car50="jaguar";
		 
		 String car51="elantra";
		 String car52="fortuner";
		 String car53="suzuki celerio";
		 String car54="hyundai i10";
		 String car55="maruti suzuki";
		 String car56="amaze";
		 String car57="tata harrier";
		 String car58="toyota fortuner";
		 String car59="chevrolet";
		 String car60="bently";
		 
		 
		 Collection obj8= new ArrayList();
			obj8.add(car1);
			obj8.add(car2);
			obj8.add(car3);
			obj8.add(car4);
			obj8.add(car5);
			obj8.add(car6);
			obj8.add(car7);
			obj8.add(car8);
			obj8.add(car9);
			obj8.add(car10);
			
			obj8.add(car11);
			obj8.add(car12);
			obj8.add(car13);
			obj8.add(car14);
			obj8.add(car15);
			obj8.add(car16);
			obj8.add(car17);
			obj8.add(car18);
			obj8.add(car19);
			obj8.add(car20);
			
			obj8.add(car21);
			obj8.add(car22);
			obj8.add(car23);
			obj8.add(car24);
			obj8.add(car25);
			obj8.add(car26);
			obj8.add(car27);
			obj8.add(car28);
			obj8.add(car29);
			obj8.add(car30);
			
			obj8.add(car31);
			obj8.add(car32);
			obj8.add(car33);
			obj8.add(car34);
			obj8.add(car35);
			obj8.add(car36);
			obj8.add(car37);
			obj8.add(car38);
			obj8.add(car39);
			obj8.add(car40);
			
			obj8.add(car51);
			obj8.add(car52);
			obj8.add(car53);
			obj8.add(car54);
			obj8.add(car55);
			obj8.add(car56);
			obj8.add(car57);
			obj8.add(car58);
			obj8.add(car59);
			obj8.add(car60);
			
			
			System.out.println(car1);
			System.out.println(car2);
			System.out.println(car3);
			System.out.println(car4);
			System.out.println(car5);
			System.out.println(car6);
			System.out.println(car7);
			System.out.println(car8);
			System.out.println(car9);
			System.out.println(car10);
			
			System.out.println(car11);
			System.out.println(car12);
			System.out.println(car13);
			System.out.println(car14);
			System.out.println(car15);
			System.out.println(car16);
			System.out.println(car17);
			System.out.println(car18);
			System.out.println(car19);
			System.out.println(car20);
			
			System.out.println(car21);
			System.out.println(car22);
			System.out.println(car23);
			System.out.println(car24);
			System.out.println(car25);
			System.out.println(car26);
			System.out.println(car27);
			System.out.println(car28);
			System.out.println(car29);
			System.out.println(car30);
			
			System.out.println(car31);
			System.out.println(car32);
			System.out.println(car33);
			System.out.println(car34);
			System.out.println(car35);
			System.out.println(car36);
			System.out.println(car37);
			System.out.println(car38);
			System.out.println(car39);
			System.out.println(car40);
			
			System.out.println(car41);
			System.out.println(car42);
			System.out.println(car43);
			System.out.println(car44);
			System.out.println(car45);
			System.out.println(car46);
			System.out.println(car47);
			System.out.println(car48);
			System.out.println(car49);
			System.out.println(car50);
			
			System.out.println(car51);
			System.out.println(car52);
			System.out.println(car53);
			System.out.println(car54);
			System.out.println(car55);
			System.out.println(car56);
			System.out.println(car57);
			System.out.println(car58);
			System.out.println(car59);
			System.out.println(car60);
			System.out.println();
			
			System.out.println("lipstick");
			System.out.println("-----------------");
			
			String lipstick1="ADS Matte Lipstick";
			String lipstick2="Lakme Absolute 3D Lipstick";
			String lipstick3="Maybelline New York ";
			String lipstick4="ADS Long-Lasting";
			String lipstick5="KRAYONS SHEER ";
			String lipstick6="Lakme Enrich Matte Lipstick ";
			String lipstick7="RENEE FAB";
			String lipstick8="ADS Matte ";
			String lipstick9="Blue Heaven ";
			String lipstick10="MATT LOOK";
			
			String lipstick11="AVARS RED edition ";
			String lipstick12="ADS Durable Water Proof";
			String lipstick13="blushia Matte Me Liquid Lipstick-Red";
			String lipstick14="Maybelline New York Super Stay";
			String lipstick15="JUICE Matte Lip ";
			String lipstick16="Blue Heaven";
			String lipstick17="Elle 18";
			String lipstick18="Blue Heaven Xpression ";
			String lipstick19="Biotique Natural ";
			String lipstick20="ADS Ultra Ceramide Matte Lipstick,";
			
			String lipstick21="Volo 5 Pcs ";
			String lipstick22="ADS Aloe Non-Smudging";
			String lipstick23="Forfor Baby Pink Matte Lipstick ";
			String lipstick24="Blue Heaven ";
			String lipstick25="Oriflame ";
			String lipstick26="AVARS Lipstick";
			String lipstick27="DREAM LINE NYN PINK MAGIC";
			String lipstick28="Krayons Sheer Matte Lipstick";
			String lipstick29="ADS PRO Ultra Smooth True Matte";
			String lipstick30="Miss Claire";
			
			String lipstick31="Volo Professional ";
			String lipstick32="ADS Natural Aloe Lipstick";
			String lipstick33="Lenphor Lasche";
			String lipstick34="LAFZ Transfer Proof & Smudge Proof";
			String lipstick35="MI Fashion Liquid Lipsticks";
			String lipstick36="PAC Retro Matte ";
			String lipstick37="MI Fashion Liquid Lipsticks Matte";
			String lipstick38="Lenphor Velvestick";
			String lipstick39="Miss Claire";
			String lipstick40="Volo";
			
			String lipstick41="ADS Durable Water Proof";
			String lipstick42="blushia Matte Me Liquid Lipstick-Red";
			String lipstick43="Maybelline New York Super Stay";
			String lipstick44="JUICE Matte Lip ";
			String lipstick45="Blue Heaven";
			String lipstick46="AVARS Lipstick";
			String lipstick47="DREAM LINE NYN PINK MAGIC";
			String lipstick48="Krayons Sheer Matte Lipstick";
			String lipstick49="ADS PRO Ultra Smooth True Matte";
			String lipstick50="Miss Claire";
			
			String lipstick51="AVARS RED edition ";
			String lipstick52="ADS Durable Water Proof";
			String lipstick53="blushia Matte Me Liquid Lipstick-Red";
			String lipstick54="Maybelline New York Super Stay";
			String lipstick55="JUICE Matte Lip ";
			String lipstick56="Blue Heaven";
			String lipstick57="Elle 18";
			String lipstick58="Blue Heaven Xpression ";
			String lipstick59="Biotique Natural ";
			String lipstick60="ADS Ultra Ceramide Matte Lipstick,";
			
			
			
			Collection obj9= new ArrayList();
			obj9.add(lipstick1);
			obj9.add(lipstick2);
			obj9.add(lipstick3);
			obj9.add(lipstick4);
			obj9.add(lipstick5);
			obj9.add(lipstick6);
			obj9.add(lipstick7);
			obj9.add(lipstick8);
			obj9.add(lipstick9);
			obj9.add(lipstick10);
			
			obj9.add(lipstick11);
			obj9.add(lipstick12);
			obj9.add(lipstick13);
			obj9.add(lipstick14);
			obj9.add(lipstick15);
			obj9.add(lipstick16);
			obj9.add(lipstick17);
			obj9.add(lipstick18);
			obj9.add(lipstick19);
			obj9.add(lipstick20);
			
			obj9.add(lipstick21);
			obj9.add(lipstick22);
			obj9.add(lipstick23);
			obj9.add(lipstick24);
			obj9.add(lipstick25);
			obj9.add(lipstick26);
			obj9.add(lipstick27);
			obj9.add(lipstick28);
			obj9.add(lipstick29);
			obj9.add(lipstick30);
			
			obj9.add(lipstick31);
			obj9.add(lipstick32);
			obj9.add(lipstick33);
			obj9.add(lipstick34);
			obj9.add(lipstick35);
			obj9.add(lipstick36);
			obj9.add(lipstick37);
			obj9.add(lipstick38);
			obj9.add(lipstick39);
			obj9.add(lipstick40);
			
			obj9.add(lipstick41);
			obj9.add(lipstick42);
			obj9.add(lipstick43);
			obj9.add(lipstick44);
			obj9.add(lipstick45);
			obj9.add(lipstick46);
			obj9.add(lipstick47);
			obj9.add(lipstick48);
			obj9.add(lipstick49);
			obj9.add(lipstick50);
			
			obj9.add(lipstick51);
			obj9.add(lipstick52);
			obj9.add(lipstick53);
			obj9.add(lipstick54);
			obj9.add(lipstick55);
			obj9.add(lipstick56);
			obj9.add(lipstick57);
			obj9.add(lipstick58);
			obj9.add(lipstick59);
			obj9.add(lipstick60);
			
			System.out.println(lipstick1);
			System.out.println(lipstick2);
			System.out.println(lipstick3);
			System.out.println(lipstick4);
			System.out.println(lipstick5);
			System.out.println(lipstick6);
			System.out.println(lipstick7);
			System.out.println(lipstick8);
			System.out.println(lipstick9);
			System.out.println(lipstick10);
			
			System.out.println(lipstick11);
			System.out.println(lipstick12);
			System.out.println(lipstick13);
			System.out.println(lipstick14);
			System.out.println(lipstick15);
			System.out.println(lipstick16);
			System.out.println(lipstick17);
			System.out.println(lipstick18);
			System.out.println(lipstick19);
			System.out.println(lipstick20);
			
			System.out.println(lipstick21);
			System.out.println(lipstick22);
			System.out.println(lipstick23);
			System.out.println(lipstick24);
			System.out.println(lipstick25);
			System.out.println(lipstick26);
			System.out.println(lipstick27);
			System.out.println(lipstick28);
			System.out.println(lipstick29);
			System.out.println(lipstick30);
			
			System.out.println(lipstick31);
			System.out.println(lipstick32);
			System.out.println(lipstick33);
			System.out.println(lipstick34);
			System.out.println(lipstick35);
			System.out.println(lipstick36);
			System.out.println(lipstick37);
			System.out.println(lipstick38);
			System.out.println(lipstick39);
			System.out.println(lipstick40);
			
			System.out.println(lipstick41);
			System.out.println(lipstick42);
			System.out.println(lipstick43);
			System.out.println(lipstick44);
			System.out.println(lipstick45);
			System.out.println(lipstick46);
			System.out.println(lipstick47);
			System.out.println(lipstick48);
			System.out.println(lipstick49);
			System.out.println(lipstick50);
			
			System.out.println(lipstick51);
			System.out.println(lipstick52);
			System.out.println(lipstick53);
			System.out.println(lipstick54);
			System.out.println(lipstick55);
			System.out.println(lipstick56);
			System.out.println(lipstick57);
			System.out.println(lipstick58);
			System.out.println(lipstick59);
			System.out.println(lipstick60);
			}

}
